# Generated by Django 5.0.4 on 2025-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['TARGET', 'SK_ID_CURR', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3'], name='ml_app_clie_TARGET_d0329b_idx'),
        ),
    ]
