# Generated by Django 4.2.23 on 2025-07-16 22:00

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_ml', '0002_rename_source_dataset_link_dataset_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLFlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(access_key='mlflow', bucket_name='mlflow', region_name='us-east-1', secret_key='mlflow'), upload_to='mlflow')),
                ('description', models.TextField()),
            ],
        ),
    ]
