# Generated by Django 4.2.23 on 2025-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_ml', '0005_bucket_remove_dataset_storage_path_dataset_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='name',
        ),
        migrations.AddField(
            model_name='bucket',
            name='endpoint',
            field=models.URLField(default='https://s3.eu-west-3.amazonaws.com'),
        ),
    ]
