# Generated by Django 4.2.23 on 2025-07-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_ml', '0009_alter_report_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='AuditReport',
        ),
        migrations.CreateModel(
            name='IARecommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommandation', models.JSONField(blank=True, default=dict, null=True)),
                ('report', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='django_app_ml.dataset')),
            ],
        ),
    ]
