# Generated by Django 4.2.23 on 2025-07-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_ml', '0010_rename_report_auditreport_iarecommandation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iarecommandation',
            old_name='recommandation',
            new_name='recommendation',
        ),
        migrations.RemoveField(
            model_name='iarecommandation',
            name='report',
        ),
    ]
