# Generated by Django 4.2.23 on 2025-07-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_ml', '0014_dataset_s3_key_alter_dataset_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlflowtemplate',
            name='model_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mlflowtemplate',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlflow_templates', to='django_app_ml.iarecommandation'),
        ),
    ]
