# Generated by Django 5.0.4 on 2025-03-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_client_ml_app_clie_target_d0329b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParquetBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='parquet')),
                ('model_link', models.CharField(max_length=50)),
            ],
        ),
    ]
